Repository dadoagency/contentful-gatsby-components, pull requests merged in 2021-01, with the labels that each got.

#57 Adding class names
  src/templates/AdvertorialType3/Hero/Hero.js
  yarn.lock
Labels: patch

#55 Embedded Block - Review B
  index.js
  src/__snapshots__/storybook.test.js.snap
  src/components/Reviews/Trustpilot/TrustpilotReview.stories.js
  src/components/Reviews/Trustpilot/TrustpilotReviewB.js
  src/utils/richText.js
  yarn.lock
Labels: major

#63 fix: updated yarn.lock
  yarn.lock
Labels: minor

#64 chore: added check that labels are present
  .github/workflows/chromatic.yml
  .github/workflows/labels.yml
  .github/workflows/push.yml
Labels: patch

#67 chore: yalc watch mode
  package.json
  src/components/ProductLinkButton/index.js
Labels: patch

#69 feat: plb svg icons added
  src/components/ProductLinkButton/index.js
Labels: patch

#70 fix: removed div wrapper from plb
  src/__snapshots__/storybook.test.js.snap
  src/components/ClientOnly/index.js
Labels: patch
